[project]
name = "tartarus"
version = "0.1.0"
description = ""
authors = [{ name = "Henry Till", email = "henrytill@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=52.0"]         # debian bullseye version
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = ["coverage>=5.1"]

[tool.black]
line-length = 120
skip-string-normalization = true
