[tool.poetry]
name = "tartarus"
version = "0.1.0"
description = ""
authors = ["Henry Till <henrytill@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
coverage = "^7.2"

[tool.poetry.scripts]
test = 'scripts:test'
coverage = 'scripts:coverage'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
skip-string-normalization = true
