EXAMPLE_DIR="${TESTDIR}/../example"
export GNUPGHOME="${EXAMPLE_DIR}/gnupg"
export ANANKE_CONFIG_DIR=$TMPDIR
export ANANKE_DATA_DIR=$TMPDIR
export PYTHONPATH="${TESTDIR}/.."
cp "${EXAMPLE_DIR}/ananke.ini" $ANANKE_CONFIG_DIR
