name: CI

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: configure
        run: |
          cat <<EOF >config.mk
          BUILD_ENV = venv
          EOF
          cat config.mk
      - run: make generate
      - run: make venv
      - run: make check
      - run: make test
  linux-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
