name: Test

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: configure
        run: |
          cat <<EOF >config.mk
          BUILD_ENV = venv
          EOF
          cat config.mk
      - run: make generate
      - run: make venv
      - run: make check
      - run: make test
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
